name: Robô Financeiro

on:
  schedule:
    # Convertido para UTC para rodar exatamente às 07:00, 11:00, 15:00 e 19:00 no Horário de Brasília
    - cron: '0 10,14,18,22, 3 * * *'
  workflow_dispatch: # Permite rodar manualmente a qualquer hora do dia pelo painel Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Criar arquivo de credenciais
        shell: python
        run: |
          import os
          with open('credenciais.json', 'w') as f:
              f.write(os.environ['GOOGLE_CREDS'])
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Rodar o Robô
        run: python main.py