name: Robô Financeiro

on:
  schedule:
    - cron: '0 13,15,17,19,21 * * 1-5'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Criar arquivo de credenciais
        shell: python
        env:
          # O nome da variável aqui (GOOGLE_CREDS) tem de ser igual ao que está no seu script
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          import os
          with open('credenciais.json', 'w') as f:
              f.write(os.environ['GOOGLE_CREDS'])

      - name: Rodar o Robô
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          LOGO_DEV_TOKEN: ${{ secrets.LOGO_DEV_TOKEN }}
          # Variáveis novas do Google Drive
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DRIVE_ROOT_FOLDER_ID: ${{ secrets.DRIVE_ROOT_FOLDER_ID }}"
        run: python app.py

